# Architecture: target-rds-santiago
# Region: la-south-2
# Generated by huaweicloud-deploy-mcp (phase 2)
# DO NOT edit manually - regenerate from architecture definition.


resource "huaweicloud_vpc" "target_vpc" {
  name = "target-vpc"
  cidr = "10.0.0.0/16"
}

resource "huaweicloud_vpc_subnet" "target_subnet" {
  name       = "target-subnet"
  vpc_id     = huaweicloud_vpc.target_vpc.id
  cidr       = "10.0.0.0/24"
  gateway_ip = "10.0.0.1"
}

resource "huaweicloud_networking_secgroup" "target_sg" {
  name = "target-sg"
}

resource "huaweicloud_rds_instance" "target_rds_postgresql" {
  name              = "target-rds-postgresql"
  flavor            = "rds.pg.c6.large.2"
  availability_zone = [var.availability_zone]

  vpc_id            = huaweicloud_vpc.target_vpc.id
  subnet_id         = huaweicloud_vpc_subnet.target_subnet.id
  security_group_id = huaweicloud_networking_secgroup.target_sg.id

  volume {
    type = "ULTRAHIGH"
    size = 40
  }

  db {
    type      = "PostgreSQL"
    version   = "16"
    user_name = "root"
    password  = var.rds_password
    port      = 5432
  }
}

resource "huaweicloud_networking_secgroup_rule" "target_sg_ingress_tcp_5432_drs" {
  direction         = "ingress"
  protocol          = "tcp"
  port_range_min    = 5432
  port_range_max    = 5432
  remote_ip_prefix  = var.allowed_drs_cidr
  security_group_id = huaweicloud_networking_secgroup.target_sg.id
  ethertype         = "IPv4"
}

resource "huaweicloud_networking_secgroup_rule" "target_sg_ingress_tcp_5432_das" {
  direction         = "ingress"
  protocol          = "tcp"
  port_range_min    = 5432
  port_range_max    = 5432
  remote_ip_prefix  = var.allowed_das_cidr
  security_group_id = huaweicloud_networking_secgroup.target_sg.id
  ethertype         = "IPv4"
}

resource "huaweicloud_networking_secgroup_rule" "target_sg_egress_all_0" {
  direction         = "egress"
  protocol          = "tcp"
  port_range_min    = 0
  port_range_max    = 65535
  remote_ip_prefix  = "0.0.0.0/0"
  security_group_id = huaweicloud_networking_secgroup.target_sg.id
  ethertype         = "IPv4"
}