#!/usr/bin/env python3
"""Host-agent-entry dream report helper.

This helper is intentionally non-LLM: it discovers bounded trajectory evidence
and writes a review-only report scaffold for the agent process that invoked the
skill. The skill caller can then summarize or amend the report without spawning
a nested LLM process.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from datetime import datetime
from pathlib import Path

try:
    from scripts.dream_llm import default_memory_dir
    from scripts.dream_signals import class_counts, scan_records
    from scripts.dream_sources import TrajectoryResult, load_trajectory, redact
except ModuleNotFoundError:  # pragma: no cover - direct script execution fallback
    from dream_llm import default_memory_dir
    from dream_signals import class_counts, scan_records
    from dream_sources import TrajectoryResult, load_trajectory, redact

# Match the official Anthropic Dreams `instructions` length limit.
MAX_INSTRUCTIONS_CHARS = 4096

# Project-root output mode writes here so it never clobbers a repo's own memory/.
PROJECT_ROOT_DIRNAME = ".maas-dreaming"
INDEX_FILE = "DREAMS.md"
POINTER_FILE = "POINTER.suggested.md"
REPORT_GLOB = "dream-agent-*.report.md"
DEFAULT_KEEP = 20

_INDEX_ENTRY_RE = re.compile(r"^- \[[^\]]+\]\(inbox/([^)]+)\)")


def normalize_instructions(raw: str | None) -> str:
    """Bound and secret-redact free-text steering instructions."""
    if not raw:
        return ""
    return redact(raw.strip())[:MAX_INSTRUCTIONS_CHARS]


def resolve_base_dir(output_mode: str, out_dir: str | None, memory_dir: Path,
                     repo_root: Path) -> Path:
    """Resolve the artifact base dir: out-dir > project-root > native memory."""
    if out_dir:
        return Path(out_dir).expanduser().resolve()
    if output_mode == "project-root":
        return repo_root / PROJECT_ROOT_DIRNAME
    return memory_dir


def report_summary(trajectory: TrajectoryResult, max_records: int) -> str:
    """One-line index summary for a report (deterministic, no secrets)."""
    if trajectory.no_trajectory:
        return f"adapter={trajectory.adapter} records=0 (no trajectory)"
    counts = class_counts(scan_records(trajectory.records, limit=max_records))
    signal = " ".join(f"{name}={counts[name]}" for name in counts)
    return (f"adapter={trajectory.adapter} records={len(trajectory.records)} "
            f"signals: {signal}")


def _existing_index_entries(index_path: Path, inbox: Path) -> list[str]:
    """Parse prior index entries, keeping only those whose report still exists."""
    if not index_path.exists():
        return []
    kept: list[str] = []
    for line in index_path.read_text(encoding="utf-8").splitlines():
        match = _INDEX_ENTRY_RE.match(line)
        if match and (inbox / match.group(1)).exists():
            kept.append(line)
    return kept


def update_index(base_dir: Path, report_path: Path, summary: str, keep: int) -> Path:
    """Rebuild the skill-owned DREAMS.md index newest-first and apply retention."""
    inbox = base_dir / "inbox"
    index_path = base_dir / INDEX_FILE
    name = report_path.name
    new_entry = f"- [{name}](inbox/{name}) — {summary}"
    prior = [e for e in _existing_index_entries(index_path, inbox)
             if not e.startswith(f"- [{name}](")]
    entries = [new_entry, *prior]

    if keep and keep > 0 and len(entries) > keep:
        for stale in entries[keep:]:
            match = _INDEX_ENTRY_RE.match(stale)
            if match:
                target = inbox / match.group(1)
                if target.name.startswith("dream-agent-") and target.exists():
                    target.unlink()
        entries = entries[:keep]

    header = [
        f"# maas-dreaming — consolidated dream reports ({INDEX_FILE})",
        "",
        "> Review-only, generated by maas-dreaming. Commit this directory to share"
        " dream findings across the team.",
        "> Never auto-applied to CLAUDE.md or MEMORY.md.",
        "",
    ]
    index_path.write_text("\n".join(header + entries) + "\n", encoding="utf-8")
    return index_path


def write_pointer(base_dir: Path) -> Path:
    """Emit a governance-safe CLAUDE.md pointer suggestion (never auto-applied)."""
    pointer_path = base_dir / POINTER_FILE
    rel = base_dir.name if base_dir.name else str(base_dir)
    pointer_path.write_text(
        "# Suggested CLAUDE.md pointer (paste once, reviewed via PR)\n\n"
        "maas-dreaming never edits CLAUDE.md. To make these shared dream reports\n"
        "auto-discoverable by every teammate's next session, add one line to the\n"
        "repo CLAUDE.md:\n\n"
        f"> See `{rel}/{INDEX_FILE}` for consolidated, review-only dream memory.\n",
        encoding="utf-8",
    )
    return pointer_path


def render_report(
    repo_root: Path,
    trajectory: TrajectoryResult,
    max_records: int,
    instructions: str = "",
) -> str:
    lines = [
        "# Dreaming Summary Report",
        "",
        f"- repo_root: `{repo_root}`",
        "- mode: `host-agent-entry`",
        f"- trajectory_adapter: `{trajectory.adapter}`",
        f"- source_path: `{trajectory.source_path or '(none)'}`",
        f"- evidence_records: {len(trajectory.records)}",
        "",
    ]
    if instructions:
        lines.extend([
            "## Steering Instructions",
            "",
            "- The caller steered this run. Apply the following when summarizing"
            " durable findings:",
            "",
            f"> {instructions}",
            "",
        ])
    lines.extend(["## Summary", ""])
    if trajectory.no_trajectory:
        lines.append(f"- No trajectory evidence was available: {trajectory.reason}.")
    else:
        lines.append("- Trajectory evidence was discovered and bounded for host-agent review.")
        lines.append("- No memory, CLAUDE.md, AGENTS.md, or global memory file was edited.")
    lines.extend(["", "## Evidence Preview", ""])
    for record in trajectory.records[:max_records]:
        lines.append(
            f"- {record.evidence_id} | time={record.timestamp or 'unknown'} | "
            f"role={record.role or '-'} | tool={record.tool or '-'} | "
            f"project_match={str(record.project_match).lower()} | {record.preview}"
        )
    if not trajectory.records:
        lines.append("- No evidence records.")
    if not trajectory.no_trajectory:
        lines.extend(["", "## Signal Scan", ""])
        hits = scan_records(trajectory.records, limit=max_records)
        counts = class_counts(hits)
        lines.append(
            "- Deterministic taxonomy over bounded evidence (review-only, "
            "no memory written): "
            + ", ".join(f"{name}={counts[name]}" for name in counts)
            + "."
        )
        if hits:
            lines.append("")
            for hit in hits:
                lines.append(
                    f"- [{hit.signal_class}] {hit.evidence_id} | "
                    f"role={hit.role} | time={hit.timestamp} | {hit.preview}"
                )
        else:
            lines.append("- No corrections/preferences/decisions/recurring signals matched.")
    lines.extend([
        "",
        "## Candidates",
        "",
        "- Review-only scaffold. The invoking host agent should add any durable candidates it can justify from the evidence.",
    ])
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Write a host-agent-entry dreaming summary report.")
    parser.add_argument("--memory-dir")
    parser.add_argument("--repo-root", required=True)
    parser.add_argument("--trajectory")
    parser.add_argument(
        "--instructions",
        default=os.environ.get("MCE_DREAM_INSTRUCTIONS"),
        help="Optional free-text steering for this run (<=4096 chars, secret-redacted).",
    )
    parser.add_argument(
        "--output-mode",
        choices=("native", "project-root"),
        default="native",
        help="native (default, ~/.claude memory) or project-root (<repo>/.maas-dreaming, git-shareable).",
    )
    parser.add_argument(
        "--out-dir",
        help="Explicit artifact base dir (e.g. ./memory). Overrides --output-mode.",
    )
    parser.add_argument(
        "--keep", type=int, default=DEFAULT_KEEP,
        help="Retain this many newest reports (0 = unlimited). Default 20.",
    )
    parser.add_argument("--max-bytes", type=int, default=200_000)
    parser.add_argument("--max-records", type=int, default=20)
    args = parser.parse_args(argv)

    repo_root = Path(args.repo_root).expanduser().resolve()
    memory_dir = Path(args.memory_dir).expanduser().resolve() if args.memory_dir else default_memory_dir(repo_root)
    memory_dir.mkdir(parents=True, exist_ok=True)
    # Trajectory evidence always comes from the native memory root, even when the
    # report is written elsewhere, so discovery/dedup stay keyed on native memory.
    trajectory = load_trajectory(args.trajectory, memory_dir, repo_root, max_bytes=args.max_bytes)
    instructions = normalize_instructions(args.instructions)

    shared = bool(args.out_dir) or args.output_mode != "native"
    base_dir = resolve_base_dir(args.output_mode, args.out_dir, memory_dir, repo_root)
    inbox = base_dir / "inbox"
    inbox.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S-%f")
    report_path = inbox / f"dream-agent-{stamp}.report.md"
    report_path.write_text(
        render_report(repo_root, trajectory, args.max_records, instructions),
        encoding="utf-8",
    )

    index_path = update_index(
        base_dir, report_path, report_summary(trajectory, args.max_records), args.keep,
    )
    if shared:
        write_pointer(base_dir)

    print(report_path)
    print(f"index: {index_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
