# Architecture: small-web-app
# Region: la-north-2
# Generated by huaweicloud-deploy-mcp (phase 2)
# DO NOT edit manually - regenerate from architecture definition.


resource "huaweicloud_vpc" "webapp_vpc" {
  name = "webapp_vpc"
  cidr = "10.0.0.0/16"
}

resource "huaweicloud_vpc_subnet" "webapp_subnet" {
  name       = "webapp_subnet"
  vpc_id     = huaweicloud_vpc.webapp_vpc.id
  cidr       = "10.0.1.0/24"
  gateway_ip = "10.0.1.1"
}

resource "huaweicloud_networking_secgroup" "webapp_sg" {
  name = "webapp_sg"
}

resource "huaweicloud_elb_loadbalancer" "webapp_elb" {
  name              = "webapp_elb"
  description       = "Shared ELB for webapp_elb"
  vpc_id            = huaweicloud_vpc.webapp_vpc.id
  availability_zone = [var.availability_zone]

  ipv4_subnet_id = huaweicloud_vpc_subnet.webapp_subnet.id
}

resource "huaweicloud_elb_listener" "webapp_elb" {
  loadbalancer_id = huaweicloud_elb_loadbalancer.webapp_elb.id
  protocol        = "TCP"
  protocol_port   = 80
}

resource "huaweicloud_elb_pool" "webapp_elb" {
  loadbalancer_id = huaweicloud_elb_loadbalancer.webapp_elb.id
  protocol        = "TCP"
  lb_method       = "ROUND_ROBIN"
  listener_id     = huaweicloud_elb_listener.webapp_elb.id
}

resource "huaweicloud_vpc_eip" "webapp_eip" {
  publicip {
    type = "5_bgp"
  }

  bandwidth {
    name        = "webapp_eip-bandwidth"
    size        = 10
    share_type  = "PER"
    charge_mode = "bandwidth"
  }
}

resource "huaweicloud_compute_instance" "webapp_ecs_1" {
  name               = "webapp_ecs-1"
  flavor_id          = "s6.large.2"
  image_name         = "AlmaLinux 9.0 64bit"
  availability_zone  = var.availability_zone
  security_group_ids = [huaweicloud_networking_secgroup.webapp_sg.id]

  network {
    uuid = huaweicloud_vpc_subnet.webapp_subnet.id
  }

  system_disk_type = "GPSSD"
  system_disk_size = 40

  admin_pass = var.ecs_admin_password
}

resource "huaweicloud_compute_instance" "webapp_ecs_2" {
  name               = "webapp_ecs-2"
  flavor_id          = "s6.large.2"
  image_name         = "AlmaLinux 9.0 64bit"
  availability_zone  = var.availability_zone
  security_group_ids = [huaweicloud_networking_secgroup.webapp_sg.id]

  network {
    uuid = huaweicloud_vpc_subnet.webapp_subnet.id
  }

  system_disk_type = "GPSSD"
  system_disk_size = 40

  admin_pass = var.ecs_admin_password
}

resource "huaweicloud_rds_instance" "webapp_rds" {
  name              = "webapp_rds"
  flavor            = "rds.mysql.n1.large.2"
  availability_zone = [var.availability_zone]

  vpc_id            = huaweicloud_vpc.webapp_vpc.id
  subnet_id         = huaweicloud_vpc_subnet.webapp_subnet.id
  security_group_id = huaweicloud_networking_secgroup.webapp_sg.id

  volume {
    type = "cloudssd"
    size = 100
  }

  db {
    type     = "mysql"
    version  = "8.0"
    password = var.rds_password
    port     = 3306
  }
}

resource "huaweicloud_obs_bucket" "webapp_uploads" {
  bucket        = "webapp-uploads-la-north-2"
  storage_class = "STANDARD"
  acl           = "private"
}

resource "huaweicloud_networking_secgroup_rule" "webapp_sg_ingress_tcp_80" {
  direction         = "ingress"
  protocol          = "tcp"
  port_range_min    = 80
  port_range_max    = 80
  remote_ip_prefix  = "0.0.0.0/0"
  security_group_id = huaweicloud_networking_secgroup.webapp_sg.id
  ethertype         = "IPv4"
}

resource "huaweicloud_networking_secgroup_rule" "webapp_sg_ingress_tcp_443" {
  direction         = "ingress"
  protocol          = "tcp"
  port_range_min    = 443
  port_range_max    = 443
  remote_ip_prefix  = "0.0.0.0/0"
  security_group_id = huaweicloud_networking_secgroup.webapp_sg.id
  ethertype         = "IPv4"
}

resource "huaweicloud_networking_secgroup_rule" "webapp_sg_ingress_tcp_3306" {
  direction         = "ingress"
  protocol          = "tcp"
  port_range_min    = 3306
  port_range_max    = 3306
  remote_ip_prefix  = "10.0.1.0/24"
  security_group_id = huaweicloud_networking_secgroup.webapp_sg.id
  ethertype         = "IPv4"
}

resource "huaweicloud_networking_secgroup_rule" "webapp_sg_egress_tcp_0" {
  direction         = "egress"
  protocol          = "tcp"
  port_range_min    = 0
  port_range_max    = 0
  remote_ip_prefix  = "0.0.0.0/0"
  security_group_id = huaweicloud_networking_secgroup.webapp_sg.id
  ethertype         = "IPv4"
}

resource "huaweicloud_elb_member" "webapp_elb_webapp_ecs_1" {
  pool_id       = huaweicloud_elb_pool.webapp_elb.id
  address       = huaweicloud_compute_instance.webapp_ecs_1.access_ip_v4
  protocol_port = 80
  subnet_id     = huaweicloud_vpc_subnet.webapp_subnet.id
}

resource "huaweicloud_elb_member" "webapp_elb_webapp_ecs_2" {
  pool_id       = huaweicloud_elb_pool.webapp_elb.id
  address       = huaweicloud_compute_instance.webapp_ecs_2.access_ip_v4
  protocol_port = 80
  subnet_id     = huaweicloud_vpc_subnet.webapp_subnet.id
}