# Architecture: source-ecs-postgresql
# Region: cn-north-4
# Generated by huaweicloud-deploy-mcp (phase 2)
# DO NOT edit manually - regenerate from architecture definition.


resource "huaweicloud_vpc" "source_vpc" {
  name = "source-vpc"
  cidr = "192.168.0.0/16"
}

resource "huaweicloud_vpc_subnet" "source_subnet" {
  name       = "source-subnet"
  vpc_id     = huaweicloud_vpc.source_vpc.id
  cidr       = "192.168.0.0/24"
  gateway_ip = "192.168.0.1"
}

resource "huaweicloud_networking_secgroup" "source_sg" {
  name = "source-sg"
}

resource "huaweicloud_compute_instance" "source_ecs_postgresql" {
  name               = "source-ecs-postgresql"
  flavor_id          = "s6.large.2"
  image_name         = "Ubuntu 22.04"
  availability_zone  = var.availability_zone
  security_group_ids = [huaweicloud_networking_secgroup.source_sg.id]

  network {
    uuid = huaweicloud_vpc_subnet.source_subnet.id
  }

  system_disk_type = "GPSSD"
  system_disk_size = 40

  admin_pass = var.ecs_admin_password
}

resource "huaweicloud_vpc_eip_associate" "source_eip_associate" {
  public_ip = huaweicloud_vpc_eip.source_eip.address
  port_id   = huaweicloud_compute_instance.source_ecs_postgresql.network[0].port
}

resource "huaweicloud_vpc_eip" "source_eip" {
  publicip {
    type = "5_bgp"
  }

  bandwidth {
    name        = "source-eip-bandwidth"
    size        = 5
    share_type  = "PER"
    charge_mode = "bandwidth"
  }
}

resource "huaweicloud_networking_secgroup_rule" "source_sg_ingress_tcp_22" {
  direction         = "ingress"
  protocol          = "tcp"
  port_range_min    = 22
  port_range_max    = 22
  remote_ip_prefix  = var.admin_ssh_cidr
  security_group_id = huaweicloud_networking_secgroup.source_sg.id
  ethertype         = "IPv4"
}

resource "huaweicloud_networking_secgroup_rule" "source_sg_ingress_tcp_5432" {
  direction         = "ingress"
  protocol          = "tcp"
  port_range_min    = 5432
  port_range_max    = 5432
  remote_ip_prefix  = var.allowed_drs_cidr
  security_group_id = huaweicloud_networking_secgroup.source_sg.id
  ethertype         = "IPv4"
}

resource "huaweicloud_networking_secgroup_rule" "source_sg_egress_all_0" {
  direction         = "egress"
  protocol          = "tcp"
  port_range_min    = 0
  port_range_max    = 65535
  remote_ip_prefix  = "0.0.0.0/0"
  security_group_id = huaweicloud_networking_secgroup.source_sg.id
  ethertype         = "IPv4"
}