-- Golden Case: customer_status_pipeline_simple
-- Source system: Snowflake Task Graph
-- Logical flow:
-- RAW_CUSTOMERS -> SILVER_CUSTOMERS -> GOLD_CUSTOMER_STATUS -> TASK_AUDIT

-- Task: T_LOAD_SILVER_CUSTOMERS
-- Source behavior:
--   Reads RAW_CUSTOMERS.
--   Filters ACTIVE_FLAG in ('Y','N').
--   Converts customer status.
--   Original Snowflake operation: INSERT INTO SELECT (non-upsert pattern).
-- Demo-safe target strategy:
--   Converted to DLI full-refresh pattern for static validation dataset.

CREATE OR REPLACE TASK T_LOAD_SILVER_CUSTOMERS
AS
INSERT INTO SILVER_CUSTOMERS (
  CUSTOMER_ID,
  CUSTOMER_NAME,
  CUSTOMER_STATUS,
  ACTIVE_FLAG,
  PROCESSED_AT
)
SELECT
  CUSTOMER_ID,
  CUSTOMER_NAME,
  CASE
    WHEN ACTIVE_FLAG = 'Y' THEN 'ACTIVE'
    WHEN ACTIVE_FLAG = 'N' THEN 'INACTIVE'
    ELSE 'UNKNOWN'
  END AS CUSTOMER_STATUS,
  ACTIVE_FLAG,
  CURRENT_TIMESTAMP() AS PROCESSED_AT
FROM RAW_CUSTOMERS
WHERE ACTIVE_FLAG IN ('Y', 'N');

-- Task: T_BUILD_GOLD_CUSTOMER_STATUS
-- Source behavior:
--   Reads SILVER_CUSTOMERS.
--   Aggregates by CUSTOMER_STATUS.
--   Produces counts by ACTIVE/INACTIVE.
--   Original Snowflake operation: CREATE OR REPLACE TABLE AS SELECT.

CREATE OR REPLACE TASK T_BUILD_GOLD_CUSTOMER_STATUS
AFTER T_LOAD_SILVER_CUSTOMERS
AS
CREATE OR REPLACE TABLE GOLD_CUSTOMER_STATUS AS
SELECT
  CUSTOMER_STATUS,
  COUNT(*) AS CUSTOMER_COUNT,
  CURRENT_TIMESTAMP() AS PROCESSED_AT
FROM SILVER_CUSTOMERS
GROUP BY CUSTOMER_STATUS;

-- Task: T_AUDIT_CUSTOMER_PIPELINE
-- Source behavior:
--   Inserts SUCCESS audit record after GOLD table is built.

CREATE OR REPLACE TASK T_AUDIT_CUSTOMER_PIPELINE
AFTER T_BUILD_GOLD_CUSTOMER_STATUS
AS
INSERT INTO TASK_AUDIT (
  PIPELINE_NAME,
  STATUS,
  CREATED_AT
)
VALUES (
  'CUSTOMER_STATUS_PIPELINE',
  'SUCCESS',
  CURRENT_TIMESTAMP()
);
