"""Authoritative LATAM region list (GL-K4 / E3-S8).

The region names are NEVER typed by hand or generated by an LLM: they are loaded
from wiki/regions.json, which must carry a provenance block naming the authoritative
source it was derived from. `verify()` re-derives the list from a raw snapshot file
(extracted mechanically) and reports drift; `drift_against_wiki()` is wired into lint.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

# Mechanical extraction pattern for Huawei Cloud region display names.
REGION_RE = re.compile(r"\bLA-[A-Z][a-z]+(?: [A-Z][a-z]+)*\d?\b")
KNOWN_CODES = re.compile(r"^[a-z0-9-]+$")


class RegionList:
    def __init__(self, data: dict):
        prov = data.get("provenance") or {}
        self.note = prov.get("note", "")
        self.expected_source = prov.get("expected_source", "")
        self.fetched_at = prov.get("fetched_at")
        self.regions: list[str] = list(data.get("regions", []))
        if not self.regions and not prov:
            raise ValueError("regions.json has no provenance block; refusing to trust it")

    @classmethod
    def load(cls, path: Path) -> "RegionList":
        return cls(json.loads(Path(path).read_text(encoding="utf-8")))

    def verify(self, snapshot_text: str) -> dict:
        """Re-derive region names from an authoritative snapshot; report drift."""
        found = sorted(set(REGION_RE.findall(snapshot_text)))
        return {"snapshot_regions": found, "stored_regions": sorted(self.regions),
                "missing_in_store": [r for r in found if r not in self.regions],
                "unbacked_in_store": [r for r in self.regions if r not in found]}

    def drift_against_wiki(self, titles: list[str]) -> list[str]:
        """Wiki region page titles that the authoritative list does not back (lint)."""
        return [t for t in titles if t not in self.regions]


def region_slug(name: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return s if KNOWN_CODES.match(s) else ""
